version: '3'
services:
  jupyter-notebook:
    container_name: jupyter-notebook
    image: jupyter/datascience-notebook
    volumes:
        - ./notebook:/home/jovyan/work
        - ./data:/home/jovyan/work/datasets
    ports:
      - "8888:8888"